import { motion } from 'framer-motion'
import { useState, useEffect } from 'react'
import ProfilePic from '../resources/images/me.png'
import MistyPic from '../resources/images/misty.png'
import DarkPitaPic from '../resources/images/dark_pita_dalle.png'
import CHIWORK2022Pic from '../resources/images/CHIWORK22_approach.png'
import CHI2022WorkshopPic from '../resources/images/user-interface-workshop.jpeg'
import Lbw2022Pic from '../resources/images/chi-lbw-2022.png'
import { useMediaQuery } from 'react-responsive'

export const Home = () => {
  // Typing animation hook
  const useTypewriter = (text: string, speed: number = 100) => {
    const [displayText, setDisplayText] = useState('')
    const [currentIndex, setCurrentIndex] = useState(0)
    const [isComplete, setIsComplete] = useState(false)

    useEffect(() => {
      if (currentIndex < text.length) {
        const timeout = setTimeout(() => {
          setDisplayText(prev => prev + text[currentIndex])
          setCurrentIndex(prev => prev + 1)
        }, speed)

        return () => clearTimeout(timeout)
      } else {
        setIsComplete(true)
      }
    }, [currentIndex, text, speed])

    return { displayText, isComplete }
  }

  const { displayText, isComplete } = useTypewriter("I am \/almost\/ graduating", 100)

  // Function to render text with colored underscores
  const renderTextWithColoredUnderscores = (text: string) => {
    return text.split(/(\/almost\/)/).map((part, index) => {
      if (part === '\/almost\/') {
        return (
          <span key={index}>
            <span style={{ color: '#E44C65', fontWeight: '500' }}>/</span>
            <span style={{ fontWeight: '500' }}>almost</span>
            <span style={{ color: '#E44C65', fontWeight: '500' }}>/</span>
          </span>
        )
      }
      return part
    })
  }

  // Responsiveness
  const isDesktop = useMediaQuery({
    query: "(min-width: 769px)",
  })

  const publications = [
    {
      title: "Misty: UI Prototyping Through Interactive Conceptual Blending",
      authors: "Yuwen Lu, Alan Leung, Amanda Swearngin, Jeffrey Nichols, Titus Barik",
      conference: "CHI 2025",
      note: "Work done during internship at Apple AIML",
      links: [
        { label: "Paper", url: "https://machinelearning.apple.com/research/interactive-prototyping" },
        { label: "Code", url: "https://github.com/ND-SaNDwichLAB/Misty" },
        { label: "Video", url: "https://x.com/yuwen_lu_/status/1850574331539276198" },
      ],
      image: MistyPic
    },
    {
      title: "From Design Transparency to Malleable Interfaces: Exploring End-User Interventions for Dark Patterns in UX",
      authors: "Yuwen Lu*, Chao Zhang*, Yuewen Yang, Yaxing Yao, Toby Jia-Jun Li (* equal contribution)",
      conference: "CSCW 2023 🏆 Best Paper Award (Top 1%)",
      note: "Left image generated by DALL-E 2, with prompt \"a picture showing the experience of a user using a browser extension that helps them change dark patterns on website interfaces\"",
      links: [
        { label: "Paper", url: "https://dl.acm.org/doi/10.1145/3637336" },
        { label: "Code", url: "https://github.com/yuwen-lu/dark-pita" },
      ],
      image: DarkPitaPic
    },
    {
      title: "A Bottom-Up End-User Intelligent Assistant Approach to Empower Gig Workers against AI Inequality",
      authors: "Toby Jia-Jun Li, Yuwen Lu, Jaylexia Clark, Meng Chen, Victor Cox, Meng Jiang, Yang Yang, Tamara Kay, Danielle Wood, Jay Brockman",
      conference: "CHIWORK '22",
      note: "",
      links: [
        { label: "Preprint", url: "https://arxiv.org/abs/2204.13842" },
        { label: "Video", url: "https://youtu.be/8zCOj9G3I_o" },
      ],
      image: CHIWORK2022Pic
    },
    {
      title: "Computational Methods for Understanding How User Interface Design Affects User Decision Making",
      authors: "Yuwen Lu, Chao Zhang, Yuewen Yang, Yaxing Yao, Toby Jia-Jun Li",
      conference: "CHI '22 Workshop",
      note: "",
      links: [],
      image: CHI2022WorkshopPic
    },
    {
      title: "Supporting Gig Workers to Choose Gig Work Utilizing Personal AI Agents",
      authors: "Yuwen Lu, Meng Chen, Jaylexia Clark, Victor Cox, Toby Jia-Jun Li",
      conference: "CHI '22 Late-Breaking Work",
      note: "",
      links: [
        { label: "Poster", url: "#" }, // Add actual URL when available
        { label: "Preprint", url: "#" }, // Add actual URL when available
      ],
      image: Lbw2022Pic
    }
  ]

  return (
    <div className="max-w-6xl mx-auto">
      {/* Hero Section - Original Bootstrap layout */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, ease: "easeInOut" }}
        className="grid md:grid-cols-2 gap-8 items-center mb-16"
        style={{ marginTop: "2rem" }}
      >
        <div className="space-y-6">
          <h1 className="title">
            {renderTextWithColoredUnderscores(displayText)}
            <span 
              className={`typing-cursor ${isComplete ? 'blink' : ''}`}
              style={{
                animation: isComplete ? 'blink 1s infinite' : 'none',
                borderBottom: '5px solid #E44C65',
                marginLeft: '2px',
                display: 'inline-block',
                width: '16px',
                height: '1em',
                verticalAlign: 'baseline',
                position: 'relative',
                top: '0.1em'
              }}
            >
              &nbsp;
            </span>
          </h1>
          <div className="space-y-4">
            <p>
              I am Yuwen, a Ph.D. Candidate in Computer Science and Engineering at the
              University of Notre Dame.
            </p>
            <p>
              I am a design engineer doing research in Human-AI Interaction. My advisor is{" "}
              <a href="https://toby.li/">Toby Li</a>.
            </p>
            {/* <p>
              Previously, I graduated with a{" "}
              <a
                href="https://www.hcii.cmu.edu/academics/mhci"
                target="_blank"
                rel="noopener noreferrer"
              >
                Master of Human Computer Interaction
              </a>{" "}
              from Carnegie Mellon University. I have a background in Computer Science and UX design & research.
            </p> */}
          </div>
        </div>

        <div className="flex justify-center">
          <img
            src={ProfilePic}
            alt="Yuwen Lu"
            className="w-80 h-80 object-cover rounded-full shadow-lg"
            style={{ 
              maxWidth: isDesktop ? "20rem" : "15rem",
              height: "auto"
            }}
          />
        </div>
      </motion.div>

      {/* Current Work Section */}
      <motion.section
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="mb-16"
      >
        <div className="text-center mb-8">
          <h2 className="text-2xl font-medium mb-8" style={{ fontSize: "1.5rem", lineHeight: "1.5" }}>
            Currently Working On...
          </h2>
        </div>
        <div className="text-center space-y-4" style={{ lineHeight: "2em" }}>
          <div>
            Exploring UI for AI (maybe{" "}
            <a
              href="https://machinelearning.apple.com/research/interactive-prototyping"
              target="_blank"
              rel="noopener noreferrer"
              className="paper-link"
            >
              more direct manipulation
            </a>
            ?),
          </div>
          <div>
            Using AI to{" "}
            <a
              href="https://arxiv.org/abs/2406.16177"
              target="_blank"
              rel="noopener noreferrer"
              className="paper-link"
            >
              support design
            </a>
            ,
          </div>
          <div>
            Dealing with{" "}
            <a
              href="https://dl.acm.org/doi/10.1145/3637336"
              target="_blank"
              rel="noopener noreferrer"
              className="paper-link"
            >
              dark patterns
            </a>
            {" "}and{" "}
            <a
              href="https://arxiv.org/abs/2406.16177"
              target="_blank"
              rel="noopener noreferrer"
              className="paper-link"
            >
              support end users
            </a>
            .
          </div>
        </div>
      </motion.section>

      {/* Publications Section */}
      <motion.section
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="mb-16"
      >
        <div className="text-center mb-8">
          <h2 className="text-2xl font-light mb-8" style={{ fontSize: "1.5rem", lineHeight: "1.5" }}>
            Publications
          </h2>
        </div>
        <div className="space-y-12">
          {publications.map((pub, index) => (
            <div
              key={index}
              className="grid md:grid-cols-4 gap-6 p-8 card-hover rounded-lg"
            >
              <div className="md:col-span-1">
                {pub.image && (
                  <img
                    src={pub.image}
                    alt={pub.title}
                    className="w-full object-cover rounded-lg"
                    style={{
                      height: isDesktop ? "10rem" : "8rem",
                      width: isDesktop ? "15rem" : "12rem"
                    }}
                  />
                )}
              </div>
              <div className="md:col-span-3 space-y-3">
                <h3 className="text-xl font-light" style={{ fontSize: "1.4rem", lineHeight: "1.9rem", marginBottom: "1.5rem" }}>
                  {pub.title}
                </h3>
                <p className="text-lg opacity-80">
                  {pub.authors.includes('Yuwen Lu*') || pub.authors.includes('**Yuwen Lu**') ? (
                    <>
                      <strong>{pub.authors.split(',')[0]}</strong>
                      {pub.authors.substring(pub.authors.indexOf(','))}
                    </>
                  ) : (
                    pub.authors.replace('Yuwen Lu', '**Yuwen Lu**').split('**Yuwen Lu**').map((part, i) => 
                      i === 1 ? <><strong key={i}>Yuwen Lu</strong>{part}</> : part
                    )
                  )}
                </p>
                <p className="text-[#E44C65] font-medium text-lg">{pub.conference}</p>
                {pub.note && (
                  <p className="text-base opacity-60 italic">{pub.note}</p>
                )}
                {pub.links.length > 0 && (
                  <div className="flex flex-wrap gap-4">
                    {pub.links.map((link, linkIndex) => (
                      <a
                        key={linkIndex}
                        href={link.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="paper-link text-lg"
                      >
                        {link.label}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </motion.section>
    </div>
  )
} 